# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc9bcc9192be3b57599f553c6e6cf9b88087005c1b55b80c20ded69d97ce92df7313c9fff9de12af93fc4b9a9ff474bd3f669ba3c7a10675e3379e835dfac5d

test:
  secret_key_base: df9c9067bc9c94b7f99fe64c59f60046389c58185da32d88a9cf1eea260c38ab565d20b853d63aa7e835735c9c12fb6c406bd8b592db2fb14b12d926b3fab04e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
